import Head from 'next/head'
import React, { FC } from 'react'
import SideNavbar from './SideNavbar/SideNavbar'
import TopNavbar from './TopNavBar/TopNavbar'

import styles from '../styles/Home.module.css'

interface Props {
  children: any
}

const Layout: FC<Props> = ({ children, ...props }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>splat | Be Efficient</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavbar />
      <SideNavbar />
      {children}
    </div>
  )
}

export default Layout