export default {
  hamburgerButton: [
    "fixed" ,
    "top-3" ,
    "right-4" ,
    "inline-flex" ,
    "items-center" ,
    "peer" ,
    "justify-center" ,
    "rounded-md",
    "p-2",
    "text-gray-900",
    "hover:text-white",
    "focus:outline-none",
    "focus:ring-inset",
    "focus:rind-white",
    "group",
    "hover:bg-gray-900",
    "z-10"
  ].join(' '),
  container: [
    "bg-white",
    "shadow-lg",
    "bg-opacity-60",
    "bg-clip-padding",
    "backdrop-blur-lg",
    "p-6",
    "w-1/2",
    "h-screen",
    "z-20",
    "fixed",
    "top-0",
    "-left-96",
    "lg:w-60",
    "lg:left-0",
    "peer-focus:left-0",
    "peer-transition",
    "ease-out",
    "delay-150",
    "duration-200"
  ].join(' ')
}