import Head from 'next/head'
import Image from 'next/image'
import SideNavbar from '../components/SideNavbar/SideNavbar'
import TopNavbar from '../components/TopNavBar/TopNavbar'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopNavbar />
      <SideNavbar />
    </div>
  )
}
