import Head from 'next/head'
import { useSession, getSession } from "next-auth/react"

import SideNavbar from '../components/SideNavbar/SideNavbar'
import TopNavbar from '../components/TopNavBar/TopNavbar'

import styles from '../styles/Home.module.css'

export default function Home() {
  const { data: session } = useSession();

  var componentToRender = <></>;
  if (session) {
    componentToRender = (
      <>
        <TopNavbar />
        <SideNavbar />
      </>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>splat | Be Efficient</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {componentToRender}
    </div>
  )
}

export async function getServerSideProps(context: any) {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/auth/signin',
        permanent: false
      }
    }
  }
  return {
    redirect: {
      destination: '/dashboard',
      permanent: false
    },
    props: {
      session
    },
  };
}
